### ISSUE TITLE
background shaking while dragging

### ISSUE THREAD

**Issue by faboweb** [briangonzalez/jquery.pep.js#160] opened 2015-04-01 12:43 UTC
If a sprite is applied to the draggable object, it shakes while dragging.

Example: http://codepen.io/faboweb/pen/VYNPbW

Not so in interactjs: http://codepen.io/faboweb/pen/OPGWbZ

**Comment by calvinjuarez** [comment] 2015-04-01 18:03
What browser are you using?

I can't replicate in Safari (8), Firefox (36,38) or Chrome (33) on Mac OS X 10.10, though I did notice some jitter on iOS Safari (8).

**Comment by faboweb** [comment] 2015-04-02 14:42
It is Chrome (41.x).
I just updated and its still this way.
Checked on:
Chrome-mobile (41) no problem
Firefox-desktop (37) no problem

**Comment by briangonzalez** [comment] 2015-06-13 16:31
I cannot reproduce. Closing for now.

**Closed by briangonzalez** 2015-06-13 16:31 UTC
